CREATE TABLE `correct` (
  `id` int(32) PRIMARY KEY NOT NULL AUTO_INCREMENT COMMENT '主键id',
  `my_id` INT(32) NOT NULL DEFAULT '0' COMMENT '批改的学员id',
  `user_id` int(16) NOT NULL DEFAULT '0' COMMENT '被批改的id',
  `homework_id` int(16) NOT NULL DEFAULT '0' COMMENT '作业id',
  `level_flag` CHARACTER(2) NOT NULL DEFAULT '' COMMENT '等级A B C D',
  `mark` VARCHAR(1000) NOT NULL DEFAULT '' COMMENT '评语',
  `create_time` TIMESTAMP NOt NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `update_time` TIMESTAMP NOt NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '创建时间'
) engine=InnoDB DEFAULT charset=utf8;